### ISSUE TITLE
Would it be possibe to port this to Forge

### ISSUE THREAD

**Issue by DraconicNEO** [tlstommy/auto-warden-subtitles#1]
title

**Comment by tlstommy** [comment]
I will look into it!

**Comment by tlstommy** [comment]
I have released a Forge version!
[Download on Github](https://github.com/tlstommy/auto-warden-subtitles/releases/tag/v2.0.0)
[Download on Modrinth](https://modrinth.com/mod/auto-warden-subtitles)
[Download on Curseforge](https://www.curseforge.com/minecraft/mc-mods/auto-warden-subtitles)
